apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 1985123573158.dkr.ecr.us-east-1.amazonaws.com/dev/helloworldjenkins/33
        ports:
        - containerPort: 80